# Generated by Django 5.0.6 on 2024-06-10 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='account',
        ),
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AlterModelTable(
            name='cartitem',
            table=None,
        ),
        migrations.DeleteModel(
            name='AddToCart',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
